DISTRICT_COURT = "D"
SUPERIOR_COURT = "S"
NOT_AVAILABLE = "N/A"

JURISDICTION_CHOICES = (
    (DISTRICT_COURT, "DISTRICT COURT"),
    (SUPERIOR_COURT, "SUPERIOR COURT"),
    (NOT_AVAILABLE, "NOT AVAILABLE"),
)

MALE = "M"
FEMALE = "F"
UNISEX = "U"
SEX_CHOICES = (
    (MALE, "Male"),
    (FEMALE, "Female"),
    (UNISEX, "Unisex"),
    (NOT_AVAILABLE, "NOT AVAILABLE"),
)

CONTACT_CATEGORIES = (("agency", "Agency"), ("attorney", "Attorney"))
