repos:
    - repo: https://github.com/adamchainz/django-upgrade
      rev: "1.15.0"
      hooks:
          - id: django-upgrade
            args: [--target-version, "4.2"]
    - repo: https://github.com/python/black
      rev: "23.12.1"
      hooks:
          - id: black
            language_version: python3.12
            args: [--config=./pyproject.toml]
    - repo: local
      hooks:
        - id: format
          name: Run formatter (prettier)
          language: system
          entry: npx prettier --write --ignore-unknown
          files:  ".*\\.(js|jsx)$"
        - id: lint
          name: Run linter (eslint)
          language: system
          entry: npx eslint --fix
          files:  ".*\\.(js|jsx)$"

