FROM node:13.12.0-alpine

RUN mkdir -p /app/frontend
WORKDIR /app/frontend

ENV PATH /app/node_modules/.bin:$PATH

COPY package*.json ./
RUN npm install
RUN npm install react-scripts@3.4.1 -g

COPY . ./

CMD ["npm", "run", "start"]
