FROM node:13.12.0-alpine

WORKDIR /app/

ENV PATH /app/node_modules/.bin:$PATH

# Copy project contents since the mounted volume is not available yet
COPY . ./

# Dependencies will be persisted in /app/ volume under /app/node_modules
RUN npm install

CMD ["npm", "run", "start"]
