version: '3.4'

services:
  django:
    build:
      context: .
      target: deploy
    env_file:
      - .envs/.production-local-testing/.django
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
  db:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: dear_petition
    image: postgres:12-alpine
  redis:
    image: redis:5-alpine
  mailhog:
    image: mailhog/mailhog:v1.0.0
