# Generated by Django 2.2.28 on 2022-05-27 15:00

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=4098)),
                ("recipient", models.CharField(max_length=4098)),
                ("sender", models.TextField(max_length=4098)),
                ("headers", models.TextField()),
                ("text", models.TextField()),
                ("html", models.TextField(blank=True)),
                ("payload", django.contrib.postgres.fields.jsonb.JSONField()),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
