# Generated by Django 2.2.28 on 2022-06-03 19:20

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Email",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=4096)),
                ("recipient", models.CharField(max_length=4096)),
                ("sender", models.CharField(max_length=4096)),
                ("headers", models.TextField()),
                ("text", models.TextField(blank=True)),
                ("html", models.TextField(blank=True)),
                ("payload", django.contrib.postgres.fields.jsonb.JSONField()),
                ("spam_score", models.FloatField(null=True)),
                ("attachment_count", models.PositiveIntegerField(default=0)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1024)),
                (
                    "content_id",
                    models.CharField(max_length=256, verbose_name="Content ID"),
                ),
                ("type", models.CharField(max_length=256)),
                (
                    "file",
                    models.FileField(
                        max_length=1024, upload_to="attachments/%Y/%m/%d/"
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="sendgrid.Email",
                    ),
                ),
            ],
        ),
    ]
