# Generated by Django 3.2.13 on 2023-01-03 22:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sendgrid", "0002_alter_email_payload"),
        ("sendgrid", "0003_alter_email_spam_score"),
    ]

    operations = []
