# Generated by Django 3.2.13 on 2023-09-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sendgrid", "0004_merge_20230103_1758"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="subject",
            field=models.CharField(blank=True, default="", max_length=4096),
        ),
    ]
