# Generated by Django 2.2 on 2019-05-18 19:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CIPRSRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=2048)),
                ("date_uploaded", models.DateTimeField(auto_now_add=True)),
                ("report_pdf", models.FileField(upload_to="ciprs/")),
                ("data", django.contrib.postgres.fields.jsonb.JSONField(blank=True)),
            ],
        )
    ]
