# Generated by Django 2.2.4 on 2020-02-08 02:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0006_auto_20191015_2329"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciprsrecord",
            name="batch",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="petition.Batch",
            ),
        ),
        migrations.AlterField(
            model_name="batch",
            name="records",
            field=models.ManyToManyField(
                related_name="batches", to="petition.CIPRSRecord"
            ),
        ),
    ]
