# Generated by Django 2.2.4 on 2020-02-08 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0008_auto_20200208_0222"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciprsrecord",
            name="batch",
            field=models.ForeignKey(on_delete="CASCADE", to="petition.Batch"),
        ),
    ]
