# Generated by Django 2.2.4 on 2020-02-08 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0010_auto_20200208_0238"),
    ]

    operations = [
        migrations.AddField(
            model_name="batch",
            name="label",
            field=models.CharField(blank=True, max_length=2048),
        ),
    ]
