# Generated by Django 2.2.4 on 2020-02-08 02:40

from django.db import migrations


def add_labels(apps, schema_editor):
    Batch = apps.get_model("petition", "Batch")
    for batch in Batch.objects.all():
        record = batch.records.order_by("date_uploaded").first()
        if record:
            print(f"Adding label {record.label} batch {batch.pk}")
            batch.label = record.label
            batch.save()


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0011_batch_label"),
    ]

    operations = [migrations.RunPython(add_labels)]
