# Generated by Django 2.2.4 on 2020-02-09 02:07

from django.db import migrations


def add_dates(apps, schema_editor):
    Batch = apps.get_model("petition", "Batch")
    for batch in Batch.objects.all():
        record = batch.records.order_by("date_uploaded").first()
        if record:
            print(f"Adding date {record.date_uploaded} batch {batch.pk}")
            batch.date_uploaded = record.date_uploaded
            batch.save()


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0013_batch_date_uploaded"),
    ]

    operations = [migrations.RunPython(add_dates)]
