# Generated by Django 2.2.4 on 2020-02-09 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petition", "0014_auto_20200209_0207"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"verbose_name_plural": "Batches"},
        ),
        migrations.AlterModelOptions(
            name="ciprsrecord",
            options={"verbose_name": "CIPRSRecord"},
        ),
        migrations.AddField(
            model_name="batch",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
