# Generated by Django 2.2.4 on 2020-02-09 02:26

from django.db import migrations


def add_user(apps, schema_editor):
    Batch = apps.get_model("petition", "Batch")
    User = apps.get_model("users", "User")
    # get first user in DB
    user = User.objects.order_by("pk").first()
    print(f"Setting all Batch.user to {user}")
    # set to all existing records
    Batch.objects.update(user=user)


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0015_auto_20200209_0226"),
    ]

    operations = [migrations.RunPython(add_user)]
