# Generated by Django 2.2.10 on 2020-04-02 16:33

from django.db import migrations
from ..constants import (
    DISTRICT_COURT,
    SUPERIOR_COURT,
    NOT_AVAILABLE
)

def get_file_no(data):
        return data["General"].get("File No", "")

def get_county(data):
    return data["General"].get("County", "")

def get_dob(data):
    return data["Defendant"].get("Date of Birth/Estimated Age", "")

def get_sex(data):
    return data["Defendant"].get("Sex", "")

def get_race(data):
    return data["Defendant"].get("Race", "")

def get_case_status(data):
    return data["Case Information"].get("Case Status", "")

def get_offense_date(data):
    return data["Case Information"].get("Offense Date", "")

def get_arrest_date(data):
    offense_date = data["Case Information"].get("Offense Date", "")
    return data["Offense Record"].get("Arrest Date", offense_date)

def get_district_court(data):
    return data["General"].get("District", "")

def get_superior_court(data):
    return data["General"].get("Superior", "")

def get_jurisdiction(data):
    is_superior = data["General"].get("Superior", "")
    is_district = data["General"].get("District", "")
    if is_superior:
        return SUPERIOR_COURT
    elif is_district:
        return DISTRICT_COURT
    else:
        return NOT_AVAILABLE

def update_existing_ciprs_records(apps, schema_editor):
    CIPRSRecord = apps.get_model("petition", "CIPRSRecord")
    records = CIPRSRecord.objects.all()
    for r in records:
        file_no = get_file_no(r.data)
        county = get_county(r.data)
        dob = get_dob(r.data)
        sex = get_sex(r.data)
        race = get_race(r.data)
        case_status = get_case_status(r.data)
        offense_date = get_offense_date(r.data)
        arrest_date = get_arrest_date(r.data)
        jurisdiction = get_jurisdiction(r.data)

        CIPRSRecord.objects.filter(pk=r.pk).update(
            file_no=file_no,
            county=county,
            dob=dob,
            sex=sex,
            race=race,
            case_status=case_status,
            offense_date=offense_date,
            arrest_date=arrest_date,
            jurisdiction=jurisdiction,
        )
    

class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0018_auto_20200402_1633'),
    ]

    operations = [
        migrations.RunPython(
            update_existing_ciprs_records, migrations.RunPython.noop
        )
    ]
