# Generated by Django 2.2.10 on 2020-04-06 03:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0021_comment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="parent",
        ),
    ]
