# Generated by Django 2.2.10 on 2020-04-09 02:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0022_remove_comment_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
