# Generated by Django 2.2.10 on 2020-05-07 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0023_comment_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="text",
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name="Petition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("AOC-CR-287", "Dismissed Charges"),
                            ("AOC-CR-288", "Not Guilty"),
                            ("AOC-CR-281", "Nonviolent Felony or Misdemeanor"),
                        ],
                        max_length=255,
                    ),
                ),
                ("county", models.CharField(max_length=255)),
                (
                    "jurisdiction",
                    models.CharField(
                        choices=[
                            ("D", "DISTRICT COURT"),
                            ("S", "SUPERIOR COURT"),
                            ("N/A", "NOT AVAILABLE"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="petition.Batch"
                    ),
                ),
            ],
        ),
    ]
