# Generated by Django 2.2.12 on 2020-05-21 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0024_auto_20200507_1941"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="petitions",
                to="petition.Batch",
            ),
        ),
    ]
