# Generated by Django 2.2.12 on 2020-05-20 01:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0024_auto_20200507_1941"),
    ]

    operations = [
        migrations.AddField(
            model_name="offense",
            name="plea",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name="offense",
            name="verdict",
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name="petition",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="petitions",
                to="petition.Batch",
            ),
        ),
    ]
