# Generated by Django 2.2.12 on 2020-05-21 17:03

from django.db import migrations
from django.db import models

from localflavor.us import us_states


def use_states_choices(apps, schema_editor):
    """
    Set the initial ordering, which can then be updated in the Admin UI.
    """
    Contact = apps.get_model("petition", "Contact")
    contacts = Contact.objects.all()
    for contact in contacts:
        for state_abbv, state in us_states.US_STATES:
            if contact.state in (state_abbv, state):
                contact.state = state_abbv
                contact.save()


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0025_auto_20200521_1624"),
    ]

    operations = [
        migrations.RunPython(use_states_choices, migrations.RunPython.noop),
    ]
