# Generated by Django 2.2.12 on 2020-05-26 15:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0027_auto_20200521_1703"),
        ("petition", "0025_auto_20200521_1343"),
    ]

    operations = []
