# Generated by Django 2.2.13 on 2020-06-16 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0028_merge_20200526_1514"),
    ]

    operations = [
        migrations.AddField(
            model_name="offense",
            name="jurisdiction",
            field=models.CharField(
                choices=[
                    ("D", "DISTRICT COURT"),
                    ("S", "SUPERIOR COURT"),
                    ("N/A", "NOT AVAILABLE"),
                ],
                default="D",
                max_length=255,
            ),
        ),
    ]
