# Generated by Django 2.2.13 on 2020-06-27 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0029_offense_jurisdiction"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="petition.Petition",
            ),
        ),
    ]
