# Generated by Django 2.2.13 on 2020-06-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0029_offense_jurisdiction"),
    ]

    operations = [
        migrations.AddField(
            model_name="offenserecord",
            name="plea",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="offenserecord",
            name="verdict",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
