# Generated by Django 2.2.13 on 2020-06-27 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0030_petition_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="offense_records",
            field=models.ManyToManyField(related_name="petitions", to="petition.OffenseRecord"),
        ),
    ]
