# Generated by Django 2.2.13 on 2020-07-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0031_petition_offense_records"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("AOC-CR-281", "AOC-CR-281"),
                    ("AOC-CR-285", "AOC-CR-285"),
                    ("AOC-CR-287", "AOC-CR-287"),
                    ("AOC-CR-288", "AOC-CR-288"),
                ],
                max_length=255,
            ),
        ),
    ]
