# Generated by Django 2.2.13 on 2020-07-25 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0032_auto_20200709_1834"),
        ("petition", "0030_auto_20200627_2339"),
    ]

    operations = []
