# Generated by Django 2.2.13 on 2020-07-25 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0033_merge_20200725_2228"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciprsrecord",
            name="additional_offenses_exist",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
