# Generated by Django 2.2.13 on 2020-08-02 14:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0034_auto_20200802_1419"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ciprsrecord",
            name="report_pdf",
        ),
    ]
