# Generated by Django 2.2.13 on 2020-11-10 03:47

from django.db import migrations
from dear_petition.users.models import User

from rest_framework.authtoken.models import Token


def forward(apps, schema_editor):
    for user in User.objects.all():
        Token.objects.create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0037_auto_20200926_2311"),
        ("users", "0002_user_has_api_access"),
    ]

    operations = [migrations.RunPython(forward, migrations.RunPython.noop)]
