# Generated by Django 2.2.20 on 2021-07-14 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0038_auto_20210412_0353"),
    ]

    operations = [
        migrations.AddField(
            model_name="offenserecord",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="batch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="batchfile",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="files",
                to="petition.Batch",
            ),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="petition.Batch",
            ),
        ),
        migrations.AlterField(
            model_name="offense",
            name="ciprs_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offenses",
                to="petition.CIPRSRecord",
            ),
        ),
        migrations.AlterField(
            model_name="offenserecord",
            name="offense",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="offense_records",
                to="petition.Offense",
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("AOC-CR-281", "AOC-CR-281"),
                    ("AOC-CR-285", "AOC-CR-285"),
                    ("AOC-CR-287", "AOC-CR-287"),
                    ("AOC-CR-288", "AOC-CR-288"),
                    ("AOC-CR-293", "AOC-CR-293"),
                ],
                max_length=255,
            ),
        ),
    ]
