# Generated by Django 2.2.24 on 2021-07-21 00:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0038_auto_20210412_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='batchfile',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='petition.Batch'),
        ),
        migrations.AlterField(
            model_name='ciprsrecord',
            name='batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='petition.Batch'),
        ),
        migrations.AlterField(
            model_name='offense',
            name='ciprs_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offenses', to='petition.CIPRSRecord'),
        ),
        migrations.AlterField(
            model_name='offenserecord',
            name='offense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offense_records', to='petition.Offense'),
        ),
    ]
