# Generated by Django 2.2.24 on 2021-12-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0039_auto_20210714_0348'),
        ('petition', '0039_auto_20210721_0031'),
    ]

    operations = [
    ]
