# Generated by Django 2.2.24 on 2021-11-14 23:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("petition", "0039_auto_20210714_0348"),
    ]

    operations = [
        migrations.CreateModel(
            name="GeneratedPetition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("AOC-CR-281", "AOC-CR-281"),
                            ("AOC-CR-285", "AOC-CR-285"),
                            ("AOC-CR-287", "AOC-CR-287"),
                            ("AOC-CR-288", "AOC-CR-288"),
                            ("AOC-CR-293", "AOC-CR-293"),
                        ],
                        max_length=255,
                    ),
                ),
                ("number_of_charges", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generated_petitions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
