# Generated by Django 2.2.24 on 2021-12-12 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0040_generatedpetition'),
        ('petition', '0040_merge_20211210_0152'),
    ]

    operations = [
    ]
