# Generated by Django 2.2.24 on 2022-01-23 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0041_merge_20211212_2109"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedpetition",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="generatedpetition",
            name="county",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="generatedpetition",
            name="jurisdiction",
            field=models.CharField(
                choices=[
                    ("D", "DISTRICT COURT"),
                    ("S", "SUPERIOR COURT"),
                    ("N/A", "NOT AVAILABLE"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="generatedpetition",
            name="race",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name="generatedpetition",
            name="sex",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("U", "Unknown"),
                    ("N/A", "NOT AVAILABLE"),
                ],
                default="N/A",
                max_length=6,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="county",
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
