# Generated by Django 2.2.27 on 2022-03-20 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0043_auto_20220319_2224"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitiondocument",
            name="previous_document",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_document",
                to="petition.PetitionDocument",
            ),
        ),
    ]
