# Generated by Django 3.2.13 on 2022-07-03 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0046_auto_20220703_2250"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petitiondocument",
            name="previous_document",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following_document",
                to="petition.petitiondocument",
            ),
        ),
    ]
