# Generated by Django 3.2.13 on 2022-10-14 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0047_alter_petitiondocument_previous_document"),
    ]

    operations = [
        migrations.AddField(
            model_name="ciprsrecord",
            name="batch_file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="petition.batchfile",
            ),
        ),
    ]
