# Generated by Django 3.2.13 on 2022-10-22 01:44

import dear_petition.petition.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0049_batch_emails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batchfile",
            name="file",
            field=models.FileField(
                upload_to=dear_petition.petition.models.get_batch_file_upload_path
            ),
        ),
    ]
