# Generated by Django 3.2.13 on 2023-01-03 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0049_auto_20221127_0002"),
        ("petition", "0050_alter_batchfile_file"),
    ]

    operations = []
