# Generated by Django 3.2.13 on 2023-03-10 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0051_merge_20230103_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='attorney',
            field=models.ForeignKey(default=None, limit_choices_to={'category': 'attorney'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='petition.contact'),
        ),
        migrations.AddField(
            model_name='batch',
            name='client',
            field=models.ForeignKey(default=None, limit_choices_to={'category': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='petition.contact'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('agency', 'Agency'), ('attorney', 'Attorney'), ('client', 'Client')], max_length=16),
        ),
    ]
