# Generated by Django 3.2.13 on 2023-03-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0051_merge_20230103_1758"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitiondocument",
            name="form_specific_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="petitiondocument",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("AOC-CR-281", "AOC-CR-281"),
                    ("AOC-CR-285", "AOC-CR-285"),
                    ("AOC-CR-287", "AOC-CR-287"),
                    ("AOC-CR-288", "AOC-CR-288"),
                    ("AOC-CR-293", "AOC-CR-293"),
                    ("Addendum 3B", "Addendum 3B"),
                ],
                default=None,
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="generatedpetition",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("AOC-CR-281", "AOC-CR-281"),
                    ("AOC-CR-285", "AOC-CR-285"),
                    ("AOC-CR-287", "AOC-CR-287"),
                    ("AOC-CR-288", "AOC-CR-288"),
                    ("AOC-CR-293", "AOC-CR-293"),
                    ("Addendum 3B", "Addendum 3B"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="petition",
            name="form_type",
            field=models.CharField(
                choices=[
                    ("AOC-CR-281", "AOC-CR-281"),
                    ("AOC-CR-285", "AOC-CR-285"),
                    ("AOC-CR-287", "AOC-CR-287"),
                    ("AOC-CR-288", "AOC-CR-288"),
                    ("AOC-CR-293", "AOC-CR-293"),
                    ("Addendum 3B", "Addendum 3B"),
                ],
                max_length=255,
            ),
        ),
    ]
