# Generated by Django 3.2.13 on 2023-04-14 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("petition", "0052_auto_20230305_1344"),
        ("petition", "0053_auto_20230407_1702"),
    ]

    operations = []
