# Generated by Django 3.2.13 on 2023-03-19 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0053_contact_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='client',
            field=models.ForeignKey(default=None, limit_choices_to={'category': 'client'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='petition.contact'),
        ),
    ]
