# Generated by Django 3.2.13 on 2023-04-25 01:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0053_alter_batch_client"),
        ("petition", "0054_merge_0052_auto_20230305_1344_0053_auto_20230407_1702"),
    ]

    operations = []
