# Generated by Django 3.2.13 on 2023-05-07 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petition', '0055_merge_20230424_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='offenserecord',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
