# Generated by Django 4.2.9 on 2024-06-01 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0061_client_alter_generatedpetition_form_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="batch",
            name="client",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="batches",
                to="petition.client",
            ),
        ),
    ]
