# Generated by Django 4.2.9 on 2024-08-08 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0062_alter_batch_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="offenserecord",
            name="agency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="petition.contact",
            ),
        ),
    ]
