# Generated by Django 4.2.9 on 2024-09-01 03:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0064_remove_contact_county_remove_contact_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ciprsrecord",
            name="arrest_date",
            field=models.DateField(blank=True, null=True, verbose_name="Arrest Date"),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="case_status",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="Case Status"
            ),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="county",
            field=models.CharField(blank=True, max_length=256, verbose_name="County"),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="data",
            field=models.JSONField(blank=True, null=True, verbose_name="Data"),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="date_uploaded",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Date Uploaded"),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="file_no",
            field=models.CharField(
                blank=True, max_length=256, verbose_name="File Number"
            ),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="has_additional_offenses",
            field=models.BooleanField(
                default=False, verbose_name="Has Additional Offenses"
            ),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="jurisdiction",
            field=models.CharField(
                choices=[
                    ("D", "DISTRICT COURT"),
                    ("S", "SUPERIOR COURT"),
                    ("N/A", "NOT AVAILABLE"),
                ],
                default="N/A",
                max_length=16,
                verbose_name="Jurisdiction",
            ),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="label",
            field=models.CharField(blank=True, max_length=2048, verbose_name="Label"),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="offense_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Offense Date"
            ),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="race",
            field=models.CharField(blank=True, max_length=256, verbose_name="Race"),
        ),
        migrations.AlterField(
            model_name="ciprsrecord",
            name="sex",
            field=models.CharField(
                choices=[
                    ("M", "Male"),
                    ("F", "Female"),
                    ("U", "Unknown"),
                    ("N/A", "NOT AVAILABLE"),
                ],
                default="N/A",
                max_length=6,
                verbose_name="Sex",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="dob",
            field=models.DateField(blank=True, null=True, verbose_name="Date of Birth"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="city",
            field=models.CharField(blank=True, max_length=64, verbose_name="City"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="county",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="County"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email Address"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=512, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="contact",
            name="phone_number",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=128,
                null=True,
                region=None,
                verbose_name="Phone Number",
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AL", "Alabama"),
                    ("AK", "Alaska"),
                    ("AZ", "Arizona"),
                    ("AR", "Arkansas"),
                    ("CA", "California"),
                    ("CO", "Colorado"),
                    ("CT", "Connecticut"),
                    ("DE", "Delaware"),
                    ("DC", "District of Columbia"),
                    ("FL", "Florida"),
                    ("GA", "Georgia"),
                    ("HI", "Hawaii"),
                    ("ID", "Idaho"),
                    ("IL", "Illinois"),
                    ("IN", "Indiana"),
                    ("IA", "Iowa"),
                    ("KS", "Kansas"),
                    ("KY", "Kentucky"),
                    ("LA", "Louisiana"),
                    ("ME", "Maine"),
                    ("MD", "Maryland"),
                    ("MA", "Massachusetts"),
                    ("MI", "Michigan"),
                    ("MN", "Minnesota"),
                    ("MS", "Mississippi"),
                    ("MO", "Missouri"),
                    ("MT", "Montana"),
                    ("NE", "Nebraska"),
                    ("NV", "Nevada"),
                    ("NH", "New Hampshire"),
                    ("NJ", "New Jersey"),
                    ("NM", "New Mexico"),
                    ("NY", "New York"),
                    ("NC", "North Carolina"),
                    ("ND", "North Dakota"),
                    ("OH", "Ohio"),
                    ("OK", "Oklahoma"),
                    ("OR", "Oregon"),
                    ("PA", "Pennsylvania"),
                    ("RI", "Rhode Island"),
                    ("SC", "South Carolina"),
                    ("SD", "South Dakota"),
                    ("TN", "Tennessee"),
                    ("TX", "Texas"),
                    ("UT", "Utah"),
                    ("VT", "Vermont"),
                    ("VA", "Virginia"),
                    ("WA", "Washington"),
                    ("WV", "West Virginia"),
                    ("WI", "Wisconsin"),
                    ("WY", "Wyoming"),
                ],
                max_length=64,
                verbose_name="State",
            ),
        ),
        migrations.AlterField(
            model_name="offense",
            name="disposed_on",
            field=models.DateField(
                blank=True, null=True, verbose_name="Disposed On Date"
            ),
        ),
        migrations.AlterField(
            model_name="offense",
            name="disposition_method",
            field=models.CharField(max_length=256, verbose_name="Disposition Method"),
        ),
        migrations.AlterField(
            model_name="offense",
            name="jurisdiction",
            field=models.CharField(
                choices=[
                    ("D", "DISTRICT COURT"),
                    ("S", "SUPERIOR COURT"),
                    ("N/A", "NOT AVAILABLE"),
                ],
                default="D",
                max_length=255,
                verbose_name="Jurisdiction",
            ),
        ),
        migrations.AlterField(
            model_name="offense",
            name="plea",
            field=models.CharField(blank=True, max_length=256, verbose_name="Plea"),
        ),
        migrations.AlterField(
            model_name="offense",
            name="verdict",
            field=models.CharField(blank=True, max_length=256, verbose_name="Verdict"),
        ),
        migrations.AlterField(
            model_name="offenserecord",
            name="action",
            field=models.CharField(max_length=256, verbose_name="Action"),
        ),
        migrations.AlterField(
            model_name="offenserecord",
            name="code",
            field=models.IntegerField(blank=True, null=True, verbose_name="Code"),
        ),
        migrations.AlterField(
            model_name="offenserecord",
            name="count",
            field=models.IntegerField(blank=True, null=True, verbose_name="Count"),
        ),
        migrations.AlterField(
            model_name="offenserecord",
            name="description",
            field=models.CharField(max_length=256, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="offenserecord",
            name="law",
            field=models.CharField(blank=True, max_length=256, verbose_name="Law"),
        ),
        migrations.AlterField(
            model_name="offenserecord",
            name="severity",
            field=models.CharField(max_length=256, verbose_name="Severity"),
        ),
    ]
