# Generated by Django 4.2.9 on 2024-10-01 22:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0066_alter_offense_plea_alter_offense_verdict"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offenserecord",
            name="action",
            field=models.CharField(max_length=256, null=True, verbose_name="Action"),
        ),
    ]
