# Generated by Django 4.2.9 on 2025-02-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("petition", "0067_alter_offenserecord_action"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offenserecord",
            name="severity",
            field=models.CharField(
                choices=[
                    ("TRAFFIC", "Traffic"),
                    ("INFRACTION", "Infraction"),
                    ("FELONY", "Felony"),
                    ("MISDEMEANOR", "Misdemeanor"),
                ],
                max_length=256,
                verbose_name="Severity",
            ),
        ),
    ]
