# Generated by Django 2.2.13 on 2020-11-16 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_api_access",
            field=models.BooleanField(default=False),
        ),
    ]
