# Generated by Django 2.2.24 on 2021-12-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_generated_petition_time",
            field=models.DateField(null=True),
        ),
    ]
