name: Lint and format code

on:
  pull_request:
  schedule:
    # run once a week on early monday mornings
    - cron: '22 2 * * 1'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm i
          python -m pip install --upgrade pip wheel
          pip install pre-commit==3.6.2
      - name: Run pre-commit
        run: pre-commit run --all-files
